version: "3.5"

services:
  app:
    container_name: finance-api
    build: .
    ports:
      - "8000:80"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: finance-redis